/*
 * This Java source file was generated by the Gradle 'init' task.
 */

import com.freesoullabs.LogtrustLogger;
import org.junit.Ignore;
import org.junit.Test;

public class LogtrustHttpSend {

  String token = "your_token_here";
  String tag = "your_tag_here";
  String domain = "your_domain_name_here";

  @Ignore
  @Test
  public void testSendSimpleEvent() {

    LogtrustLogger httpLogger = new LogtrustLogger.Builder()
            .domain(domain)
            .token(token)
            .defaultTag(tag)
            .build();
    int max = 0;
    for (int i = 0; i < max; i++)
      httpLogger.send("hello http data " + i);

  }


  @Ignore
  @Test
  public void testSendSeveralEvents() {

    LogtrustLogger httpLogger = new LogtrustLogger.Builder()
            .domain(domain)
            .token(token)
            .defaultTag(tag)
            .build();
    int max = 10;
    String[] data = new String[10];
    for (int i = 0; i < max; i++){
      data[i] = "Hello world Buffered Data = " + i;
    }

    httpLogger.sendAll(data);

  }
}
